apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adminer-deployment
  name: adminer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: adminer-deployment
  type: NodePort
status:
  loadBalancer: {}
